.travis.yml
packages/app/.gitignore
packages/app/jest.config.js
packages/app/package.json
yarn.lock

refacto: run jest test again

---

.env.sample

add env.APP_URL

---

packages/api/app.js

fix: increase JSON POST limit

---

packages/api/routes/inscription.js

fix(api): POST /inscription/mandataires must return a promise

---

package.json
yarn.lock

chore(deps): upgrade to lerna 1.13.1

---

packages/app/src/components/tiComponents/FilterMesuresMap.js

---
More `styled-components@4` friendly version.

refacto(frontend): better map zoom handling

---

codecov.yml

chore(codecov): add monorepo codecov config

---

.dockerignore
Dockerfile

build(docker): add master image to build them all

---

packages/api/Dockerfile
packages/api/package.json
packages/app/.gitignore
packages/app/Dockerfile

build(docker): use master image to build app and api images

---

packages/app/src/components/inscription/Form.js
packages/app/src/components/inscription/FormMandataire.js
packages/app/src/components/inscription/InscriptionIndividuel.js

fix(app): handle phone and postcode validation without alerts

---

docker-compose.yaml

feat(docker): use postgres 11 :tada:

---

packages/knex/seeds/test/0000-users.js

test(seeds): name the service profile Mélanie ❤

---

packages/api/routes/inscription.js

fix(api): async/await try/catch GET /inscription/tis

---

packages/api/routes/admin.js

fix(api): try/catch GET /admin/mandataires

---

packages/api/db/queries/admin.js

fix(api): explicite mandataires data order on getMandataires fct

---

packages/api/__test__/e2e/inscription/POST_inscription.test.js
packages/api/__test__/e2e/inscription/__snapshots__/POST_inscription.test.js.snap
packages/api/routes/inscription.js
packages/app/src/components/communComponents/Api.js
packages/app/src/components/inscription/Form.js

---
Including
- POST /inscription/mandataires must return 422 on mismatch
- POST /inscription/mandataires must return 409 on conflict
Closes #43
Closes #44

refacto(api): async await the POST inscription mandataires route

---

packages/knex/seeds/test/0000-users.js

test(seeds): set user reset_password_expires to now + 5min

---

packages/knex/seeds/test/0000-users.js

test(seeds): remove implicite active true

---

.gitlab-ci.yml

ci(gitlab): add gitlab

---

packages/app/package.json
yarn.lock

feat(app): actually remove cypress in favour of the optional e2e pkg

---

.travis.yml

Try to have all the commits for the release Change Log

ci(travis): disable git --depth

---

packages/app/src/components/loginComponents/LoginForm.js

Vu qu'on a beaucoup d'erreurs de login, je me suis dit que ce serait pas mal de stocker le login côté client ?

feat(app): remember username on login

---

optional/e2e/cypress/integration/.utils.js

---
\following #81
Some test fail due to existing username in the localstorage

test(e2e): clear the username field before typing inside it

---

optional/e2e/cypress/integration/tis.spec.js

test(e2e): re-enable TI tests

---

.travis.yml

---
see https://github.com/cypress-io/cypress/issues/867

ci(travis): disable video rec on e2e tests

---

.travis.yml
lerna.json

chore(lerna): make lerna publish the changelog

---

.gitlab-ci.yml
Dockerfile
optional/e2e/.eslintrc.yml
optional/e2e/package.json
optional/e2e/yarn.lock
packages/api/.eslintrc.yml
packages/api/package.json
packages/app/.eslintrc.yml
packages/app/package.json
packages/app/src/components/common/nomination.js
packages/app/src/components/communComponents/Api.js
packages/app/src/components/inscription/Form.js
packages/app/src/components/inscription/InscriptionPrepose.js
packages/app/src/components/loginComponents/ForgotPasswordForm.js
packages/app/src/components/mandataires/TableMesures.js
packages/app/src/components/mandataires/modals/EditMandataire.js
packages/app/src/components/mandataires/modals/EditMesure.js
packages/app/src/components/tiComponents/TableTi.js
packages/app/src/components/tiComponents/actions/mesures.js
packages/app/src/components/tiComponents/actions/user.js
packages/app/src/components/tiComponents/index.js
packages/jest-environment-knex/package.json
packages/jest-environment-knex/tslint.json
packages/knex/.eslintrc.yml
packages/knex/__test__/.eslintrc.yml
packages/knex/package.json

ci(gitlab): add more code quality jobs

---

README.md

docs(README): test and build minimal documentation

---

.gitlab-ci.yml
codecov.yml
packages/api/jest.config.js
packages/app/jest.config.js

ci(gitlab): try to fixing the coverage spamming

---

packages/api/__test__/e2e/routes.test.js

---
Thanks to https://codeshack.io/json-sorter/

test(api): sort access check map by url key

---

packages/api/__test__/e2e/admin/GET_mandataires.test.js
packages/api/__test__/e2e/admin/GET_tis.test.js
packages/api/__test__/e2e/admin/PUT_user.test.js
packages/api/__test__/e2e/admin/__snapshots__/GET_mandataires.test.js.snap
packages/api/__test__/e2e/admin/__snapshots__/GET_tis.test.js.snap
packages/api/__test__/e2e/admin/__snapshots__/PUT_user.test.js.snap
packages/api/routes/admin.js

test(api): add /api/v1/admin/* tests

---

.gitlab-ci.yml

ci(gitlab): test without api alias

---

Dockerfile
README.md
package.json

build(monorepo): add partial build on postinstall

---

packages/api/db/queries/mesures.js

fix(api): replace parseInt by Number

---

.gitlab-ci.yml

ci(gitlab): ignore script before linting @optional/e2e

---

packages/knex/migrations/20190528110944_add_services_for_mandataires_service.js

---
Migration and seed files should be standalone

fix(knex): remove dependence on api files

---

.gitlab-ci.yml
docker-compose.override.yaml.sample
packages/app/nginx.conf

revert(gitlab): back to 274aae7 service config

---

.env.test
.gitlab-ci.yml
.travis.yml
Dockerfile
docker-compose.override.yaml.sample
docker-compose.test.yaml
packages/app/Dockerfile
packages/app/nginx.conf
packages/app/scripts/entrypoint.sh
packages/app/src/components/loginComponents/LoginForm.js

build(docker): sed the frontend artifact to config the API_URL

---

optional/e2e/.dockerignore
optional/e2e/Dockerfile
package.json

build(e2e): update docker file build

---

optional/e2e/cypress/integration/admin.spec.js
packages/api/__test__/e2e/admin/__snapshots__/GET_mandataires.test.js.snap
packages/api/__test__/e2e/admin/__snapshots__/GET_tis.test.js.snap
packages/knex/seeds/test/0000-users.js

---
\following https://github.com/SocialGouv/emjpm/blob/0ca4058c0ebfab840f8051758c0ac2feb893df1b/packages/api/routes/admin.js#L112

test(e2e): update admin tests and user test seed

---

optional/e2e/cypress/integration/inscription.spec.js

test(e2e): update inscription tests

---

optional/e2e/cypress/integration/mandataires.spec.js

test(e2e): update mandataires tests

---

packages/app/src/components/tiComponents/MapTi.js

fix(app): prevent '_leaflet_pos' of undefined error

---

docker-compose.yaml

fix(docker): use a fixed container name for DB

---

packages/api/routes/mandataireMesures.js
packages/app/src/components/mandataires/TableMesures.js
packages/app/src/components/mandataires/indiPrepo.js
packages/app/src/components/mandataires/service.js
packages/app/src/components/tiComponents/actions/mandataire.js
packages/app/src/components/tiComponents/actions/mesures.js
packages/app/src/components/tiComponents/index.js
packages/app/src/components/tiComponents/modals/CloseMesureAttente.js
packages/app/src/components/tiComponents/modals/index.js
packages/app/src/components/tiComponents/reducers/mandataire.js

feat(magistrats): ETQ magistrat je souhaite pouvoir annuler une mesure.

---

docker-compose.override.yaml.sample

this should be reported to dev/prod environments

fix: add persistent volume for cvs upload

---

packages/api/Dockerfile

build(api): copy from local files

---

docker-compose.test.yaml
docker-compose.yaml
packages/api/package.json
packages/app/package.json
yarn.lock

test(docker): fix graphql-engine api endpoint

---

packages/app/scripts/entrypoint.sh

build(app): replace env var in all html files

---

.gitlab-ci/env.sh
.k8s/app/deployment.yml
.k8s/certificate/certificate.yml
Dockerfile

 build(k8s): use HASURA_URL as GRAPHQL_SERVER_URI

---

docker-compose.yaml

---
Fixes annoying `%%WHATEVER_URL%%` replacement :kiss:

build(docker): do not mount the hasura migrations [skip-ci]

---

packages/app/next.config.js
packages/app/scripts/entrypoint.sh

feat(app): use exportTrailingSlash next option

---

packages/app/package.json
packages/app/src/components-v2/ServiceMesures/ServiceEditMesure.js
packages/app/src/components-v2/ServiceMesures/ServiceMesures.js
packages/app/src/components-v2/ServiceMesures/mutations.js
packages/app/src/components-v2/ServiceMesures/utils.js
packages/app/src/constants/mesures.js
yarn.lock

WIP: feat(service-edit-mesure): add data component

---

.k8s/hasura/deployment.yml

---
It seems like the labels can't change in the `extensions/v1beta1` version...

fix(k8s): update hasura deployment api version

---

.gitlab-ci/stages/deploy.yml
.k8s/graphql-server/.k8s-deploy-graphql-server.yml
.k8s/hasura/deployment.yml

fix(k8s): communication from graphql-server to hasura

---

packages/knex/knexfile.js

---
Following 1fa9eae7c893091e4b86ed7701cb53cf77c42da6

chore(knex): remove seed config in production

---

.k8s/api/deployment.yml
.k8s/graphql-server/deployment.yml

build(k8s): pass NODE_ENV to the node pods

---

.gitlab-ci/extends.yml
.k8s/api/.k8s-deploy-api.yml
.k8s/app/.k8s-deploy-app.yml
.k8s/graphql-server/.k8s-deploy-graphql-server.yml
.k8s/hasura/.k8s-deploy-hasura.yml
.k8s/postgres/.k8s-deploy-postgres.yml

refactor(k8s): set namespace preference on kubectl

---

.k8s/postgres/values-postgresql.yaml

refactor(k8s): try using our own postgres image ;)

---

.k8s/app/deployment.yml

build(k8s): the app api uses the same protocol

---

.k8s/postgres/.k8s-deploy-postgres.yml

ci(gitlab): remove previous configmap if exists

---

.k8s/postgres/values-postgresql.yaml
.k8s/secret-dev.yml

build(k8s): add extra env secret var for postgres

---

.k8s/postgres/backup/configmap/backup.sh
.k8s/postgres/backup/cronjob.yml

feat(k8s): anonymize the dump

---

.k8s/api/deployment.yml
.k8s/app/deployment.yml
.k8s/graphql-server/deployment.yml
.k8s/secret-dev.yml

feat(k8s): add sentry public dns

---

packages/api/package.json
packages/graphql-server/package.json

build: enable ncc source maps

---

packages/app/pages/_app.js

feat(app): use the tool factory matomo

---

.gitlab-ci/stages/deploy.yml

ci(gitlab): better default quota suppression

---

.k8s/api/deployment.yml
.k8s/app/deployment.yml
.k8s/graphql-server/deployment.yml
.k8s/hasura/deployment.yml
.k8s/postgres/backup/configmap/anonymous.sh
.k8s/postgres/backup/cronjob.yml
.k8s/postgres/dataset/job-inject-dataset.yml
.k8s/postgres/values-postgresql.yaml
.k8s/quota.yml

feat(k8s): recalcul quota

---

.k8s/secret-dev.yml

fix(k8s): use secure SMTP port

---

.gitlab-ci/stages/deploy.yml
.k8s/api/deployment.yml
.k8s/secret-dev.yml

fix(k8s): add APP_URL environment variable

---

packages/app/src/lib/apollo/init-apollo.js

cf: https://github.com/apollographql/apollo-client/issues/2983

fix(next-ssr): disable ssrmode so fetch policy can be network only

---

packages/app/src/components-v2/ServiceMesures/ServiceMesures.js
packages/app/src/components-v2/ServiceMesures/queries.js
packages/app/src/components-v2/ServicesFilters/ServicesFilters.js
packages/app/src/components-v2/ServicesFilters/context/FiltersContext.js
packages/app/src/components-v2/hooks/index.js
packages/app/src/components-v2/hooks/useDebounce.js

add search input in mesures list with debounce delay.

feat(service): add search input in mesures list

---

.k8s/api/deployment.yml
.k8s/app/deployment.yml
.k8s/graphql-server/deployment.yml
.k8s/hasura/deployment.yml
.k8s/metabase/values.yaml
.k8s/postgres/backup/cronjob.yml
.k8s/postgres/dataset/job-inject-dataset.yml
.k8s/postgres/values-postgresql.yaml
.k8s/quota.yml

feat(k8s): dream quota

---

.k8s/postgres/backup/configmap/anonymous.sh
.k8s/postgres/backup/configmap/backup.sh
.k8s/postgres/backup/configmap/status.sh
.k8s/postgres/backup/configmap/wait_for_status.sh
.k8s/postgres/backup/cronjob.yml

ci(gitlab): rework prod backup job

---

packages/api/package.json
packages/knex/package.json
yarn.lock

chore(deps): update dependency jest-environment-node to 24.9.0

---

.k8s/postgres/.k8s-deploy-postgres.yml
.k8s/postgres/restore/restore-job.yml
docker/postgres/postgres-init.sh

feat(postgres): make the init script replayable

---

.gitlab-ci/extends.yml
.gitlab-ci/stages/prepare.yml

ci(gitlab): speed up the prepare stage with only changes

---

.gitlab-ci/stages/quality.yml

ci(gitlab): speed up the quality stage with only changes

---

.gitlab-ci/stages/register.yml

ci(gitlab): speed up the register stage with only changes

---

.gitlab-ci/stages/quality.yml

revert: ci(gitlab): speed up the quality stage with only changes

---

.gitlab-ci/extends.yml

This reverts commit 7c3658833f00fc4f168ced5440f13bcd571e52ce.

Revert "ci(gittlab): update kubectl:0.11.0, helm:0.11.0 (#920)"

---

package.json
yarn.lock

chore(deps): update dependency husky to 3.0.9

---

packages/app/package.json
yarn.lock

chore(dep): update emjpm-ui

---

packages/api/package.json
packages/app/package.json
yarn.lock

---
Following missing ref in `production` mode for : 
https://github.com/SocialGouv/emjpm/blob/c4764a274781b76be310462e9697891176fbe7a9/packages/api/email/reservation-email.js#L1

fix(api): add date-fns dependency

---

packages/api/package.json
packages/app/package.json
yarn.lock

chore(deps): update dependency @babel/* to ^7.7.5

---

packages/app/package.json
yarn.lock

---
`@sentry/browser` is a real dependency

fix(deps): update dependency @sentry/browser to ^5.10.2

---

packages/app/package.json
yarn.lock

fix(deps): update dependency next to ^9.1.5

---

packages/app/src/components/Commons/LinkButton.js

fix(app): there is not router sometimes

---

packages/app/src/components/MandatairesEditInformations/mutations.js

Revert "WIP: fix(mandataire-edit): add mutation for missing form fields"

---

packages/hasura/Dockerfile
packages/hasura/config.yaml

---
see https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html#how-do-i-turn-off-telemetry-opt-out

chore(hasura): turn off telemetry

---

packages/knex/__test__/index.test.js

test(knex): allow knex tests to take up to 25s

---

.travis.yml

ci(travis): update travis build caching

---

.gitlab-ci/variables.yml

ci(gitlab): add PROJECT variable

---

packages/hasura/Dockerfile

build(hasura): use default hasura/graphql-engine docker cwd and entry

---

.env.sample
docker-compose.yaml

---
```
$ yarn dev
$ docker-compose up
=> use same localhost
```

build(docker): tell hasura to use network host in dev

---

docker-compose.build.yaml

build(docker): correct docker-compose.build.yaml

---

.env.build

build(env): change DATABASE_URL when running build

---

.k8s/postgres/.k8s-deploy-postgres.yml
.k8s/postgres/restore/restore-job.yml

ci(gitlab): restore restore job

---

.gitlab-ci/stages/deploy.yml
.k8s/metabase/.k8s-deploy-metabase.yml

ci(gitlab): set the env before deploying metabase

---

.gitlab-ci/extends.yml

ci(gitlab): remove workspace dependencies on single package install

---

packages/app/next.config.js
packages/app/package.json
yarn.lock

https://github.com/zeit/next-plugins/issues/377

feat(sourcemap): use canary next-source-maps to gen missing sourcemap

---

packages/app/next.config.js
packages/app/package.json
yarn.lock

Revert "feat(sourcemap): use canary next-source-maps to gen missing sourcemap"

---

.gitlab-ci/variables.yml

ci(gitlab): reduce git fetch depth to 5 by default

---

packages/api/__test__/e2e/webhooks/emailReservation.test.js
packages/api/src/email/reservation-email.js
packages/api/src/routes/webhook.js

Fix https://sentry.fabrique.social.gouv.fr/incubateur/emjpm/issues/2590/?query=is:unresolved%20etablissement

fix(webhook): set mesure reservation email default ti value

---

.gitlab-ci.yml

ci(hasura): change requested memory/CPU in dev

---

.gitlab-ci.yml
packages/graphql-server/.k8s.values.yml

ci(graphql-server): change requested memory/CPU in dev

---

.gitlab-ci.yml

ci(app): change requested memory/CPU in dev

---

.gitlab-ci.yml

ci(api): change requested memory/CPU in dev

---

packages/api/__test__/e2e/user/forgotPassword.test.js
packages/api/src/app.js
packages/api/src/controllers/user/forgot-password.js
packages/api/src/utils/sentry.js
packages/app/src/components/ForgotPassword/ForgotPassword.js

https://sentry.fabrique.social.gouv.fr/incubateur/emjpm/issues/2070/

fix(forgot-password): handle forgot password user notfound and add tests

---

README.md
lerna.json
package.json

e2e: propose yarn --cwd instead of lerna complex args

---

packages/app/package.json

chore(app): next build without extra memory

---

packages/app/src/components/MandataireMesure/MandataireMesure.js
packages/app/src/components/MesureContext/index.js
packages/app/src/components/MesureContext/mesureFormatter.js
packages/app/src/components/ServiceMesure/ServiceMesure.js

feat(pays): affichage pays service/individuel

---

packages/app/pages/mandataires/index.js
packages/app/pages/services/index.js
packages/app/src/components/Layout/LayoutMandataire.js
packages/app/src/components/Layout/LayoutServices.js

fix(menu): individuel/service menu ui #1708

---

packages/app/src/components/AdminTribunaux/AdminTribunaux.js
packages/app/src/components/AdminTribunaux/queries.js

Fix https://github.com/SocialGouv/emjpm/issues/1704

feat(admin): #1704 gestion tribunaux immutable

---

packages/app/src/components/MandataireMesureClose/MandataireMesureCloseForm.js

Quick fix pour #1715 mais il faudrait un vrai composant datepicker je pense @tglatt

fix(mesure): input date with safari browser - it fixes #1715

---

packages/app/pages/services/map.js
packages/app/src/components/Map/MapCluster.js
packages/app/src/components/Map/index.js
packages/app/src/components/ServiceMap/ServiceMap.js
packages/app/src/components/ServiceMapPanelMesures/ServiceMapPanelMesures.js
packages/app/src/components/ServiceMapPanelMesures/queries.js

feat(map): affichage des clusters sur la carte #1716

---

docker-compose.build.yaml
docker-compose.built.yaml
packages/app/src/components/MagistratMesureAdd/MagistratMesureAddForm.js
packages/app/src/components/MagistratMesureAdd/mutations.js
packages/app/src/components/MagistratMesureDelete/MagistratMesureDeleteForm.js
packages/app/src/components/MagistratMesureDelete/mutations.js
packages/graphql-server/.k8s.values.yml
packages/graphql-server/src/config/config.ts
packages/graphql-server/src/datasource/auth-datasource.ts
packages/graphql-server/src/datasource/mandataire.api.ts
packages/graphql-server/src/datasource/mesure.api.ts
packages/graphql-server/src/datasource/service.api.ts

fix(mesure): refresh mesures count

---

packages/app/pages/mandataires/map.js
packages/app/src/components/MandataireMap/MandataireMap.js
packages/app/src/components/MandataireMapPanelMesures/MandataireMapPanelMesures.js
packages/app/src/components/MandataireMapPanelMesures/queries.js
packages/app/src/components/ServiceMapPanelMesures/ServiceMapPanelMesures.js

Même chose que service, côté mandataire:  #1716

feat(mandataires/map): affichage des clusters sur la carte #1716

---

packages/app/src/components/MagistratMandataireMap/MagistratMandataireMapContent.js
packages/app/src/components/Map/MapCluster.js

feat(magistrats/map): affichage du cluster de mesures sur la carte #1739

---

packages/api/src/routes/hasura-actions/mesures-import/actionsMesuresImporter.js
packages/api/src/utils/file/excelParser.js
packages/app/src/components/EnqueteImport/SingleImportFilePicker.js
packages/app/src/components/MesureImport/fileReader.js

Fix https://github.com/SocialGouv/emjpm/issues/1816

fix(upload): replace binary upload and encoding method

---

packages/app/.eslintrc.yml
packages/app/pages/mandataires/enquetes/[enquete_id]/index.js
packages/app/src/components/Enquete/Enquete.js
packages/app/src/components/Enquete/EnqueteIndividuel/EnqueteIndividuel.js
packages/app/src/components/Enquete/EnqueteIndividuel/EnqueteIndividuelWelcome.js
packages/app/src/components/Enquete/EnqueteIndividuel/enqueteIndividuelMenuBuilder.service.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformations.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsAgrements.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsFormation.js
packages/app/src/components/Enquete/EnqueteIndividuelPrestationsSociales/EnqueteIndividuelPrestationsSociales.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationsCuratelle.js
packages/app/src/components/Enquete/queries.js
packages/app/src/components/EnqueteImport/EnqueteImportPanel.js
packages/app/src/components/MenuStepper/MenuStepper.js
packages/app/src/util/urlQueryParser.service.js

feat(enquete): extract control & content from MenuStepper #1832

---

packages/app/src/components/MenuStepper/MenuStepper.js

Fix https://github.com/SocialGouv/emjpm/issues/1848

feat(enquete): update menu errors ui

---

.gitlab-ci.yml

ci(gitlab): make cache follow the yarn.lock changes

---

packages/api/src/routes/hasura-actions/enquete-import/parser/enqueteExcelParser.js
packages/api/src/routes/hasura-actions/enquete-import/parser/enqueteExcelParserInformationsMandataire.js
packages/api/src/routes/hasura-actions/enquete-import/parser/enqueteExcelSchemaUtil.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsForm.js

Lié à https://github.com/SocialGouv/emjpm/issues/1811

feat(enquete): import individuel tab infos generales #1801

---

packages/api/src/models/EnqueteReponsesAgrementsFormations.js
packages/api/src/routes/hasura-actions/enquete-import/actionsEnqueteImporter.js
packages/api/src/routes/hasura-actions/enquete-import/constants/ENQ_REP_AGREMENTS_FORMATIONS.const.js
packages/api/src/routes/hasura-actions/enquete-import/constants/ENQ_REP_INFO_MANDATAIRE.const.js
packages/api/src/routes/hasura-actions/enquete-import/constants/enqueteKeysBuilder.service.js
packages/api/src/routes/hasura-actions/enquete-import/parser/enqueteExcelParser.js
packages/api/src/routes/hasura-actions/enquete-import/parser/enqueteExcelParserAgrementsFormations.js
packages/api/src/routes/hasura-actions/enquete-import/repository/enqueteImportRepository.js
packages/api/src/routes/hasura-actions/enquete-mandataire-individuel/queries.js
packages/api/src/routes/hasura-actions/enquete-mandataire-individuel/requests.js
packages/api/src/routes/hasura-actions/enquete-mandataire-individuel/schemas.js
packages/api/src/routes/hasura-actions/hasura-actions.routes.js
packages/app/package.json
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsAgrements.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsAgrementsForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/mutations.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/queries.js
packages/app/src/components/Enquete/constants/ENQ_REP_AGREMENTS_FORMATIONS_FORM.const.js
packages/app/src/components/Enquete/constants/ENQ_REP_INFO_MANDATAIRE_FORM.const.js
packages/app/src/components/Enquete/constants/enqueteKeysBuilder.service.js
packages/app/src/components/Enquete/constants/index.js
packages/app/src/lib/validationSchemas/enqueteMandataireIndividuelSchema.js
packages/hasura/migrations/metadata.yaml
packages/knex/migrations_v2/20200526173100_upd_enquete_reponses_agrements_formations.js
packages/knex/migrations_v2/20200527165608_enquete_response_constraint.js
yarn.lock

Lié à https://github.com/SocialGouv/emjpm/issues/1811

feat(enquete): import individuel tab agrements formations #1801

---

packages/app/src/components/Enquete/EnqueteIndividuel/EnqueteIndividuelSubmit.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsAgrements.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/mutations.js

Finalisation de l'onglet "agréments"

feat(enquete): import individuel tab agrements #1801

---

packages/api/src/models/EnqueteReponsesActivite.js
packages/api/src/routes/hasura-actions/enquete/common/excel-parser/enqueteExcelParserActivite.js
packages/api/src/routes/hasura-actions/enquete/common/excel-parser/index.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel-import/mandataireIndividuelEnqueteExcelParser.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel-import/mandataireIndividuelEnqueteRepository.js
packages/knex/__test__/__snapshots__/index.test.js.snap
packages/knex/migrations_v2/20200601162135_update_enquete_reponses_activite.js

Import de l'onglet "activités".
Reste à refaire une passe sur le formulaire  pour ajouter les champs manquants.

feat(enquete): import individuel activite #1801

---

packages/app/src/components/Enquete/EnqueteIndividuel/EnqueteIndividuelWelcome.js

feat(enquete-import): style import button

---

packages/api/src/routes/hasura-actions/enquete/common/excel-parser/enqueteExcelParserActivite.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsFormationForm.js
packages/app/src/components/IndividuelInformationExercice/IndividuelInformationExerciceForm.js
packages/app/src/components/IndividuelInformationExercice/IndividuelInformationExerciceView.js

fix(enquete): import file for individuel

---

packages/api/src/routes/hasura-actions/enquete/common/enquete-status/activite/enqueteActiviteStatus.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/agrements_formations/enqueteAgrementsFormationsStatus.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/enqueteSchemaUtil.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/informations_mandataire/enqueteInformationsMandatairesStatus.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/modalites-exercice/enqueteModalitesExerciceStatus.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/populations/populationsStatus.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/prestations-sociales/prestationsSocialesStatus.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel/queries.js

feat(enquete): validation fix + log validation errors on server side

---

packages/api/src/models/EnqueteReponsesPreposePersonelFormation.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/index.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/prepose_personel_formation/enquetePreposePersonelFormationStatus.js
packages/api/src/routes/hasura-actions/enquete/common/excel-parser/enqueteExcelParserPreposePersonelFormation.js
packages/api/src/routes/hasura-actions/enquete/common/excel-parser/index.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose-import/preposeEnqueteExcelParser.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose-import/preposeEnqueteRepository.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/enqueteMandatairePrepose.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/enqueteMandatairePreposeStatus.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/mutations.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/queries.js
packages/app/src/components/Enquete/EnqueteIndividuel/EnqueteIndividuel.js
packages/app/src/components/Enquete/EnquetePrepose/EnquetePrepose.js
packages/app/src/components/Enquete/EnquetePrepose/enquetePreposeMenuBuilder.service.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationMjpm.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationMjpmForm.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/index.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/mutations.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/queries.js
packages/app/src/util/index.js
packages/hasura/metadata/tables.yaml
packages/knex/migrations_v2/20200609083259_create_enquete_reponses_prepose_personel_formation.js

Début de https://github.com/SocialGouv/emjpm/issues/1916

feat(enquete): prepose personel et formation

---

packages/api/src/models/EnqueteReponsesPreposePersonelFormation.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/prepose_personel_formation/enquetePreposePersonelFormationStatus.js
packages/api/src/routes/hasura-actions/enquete/common/excel-parser/enqueteExcelParserPreposePersonelFormation.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel/enqueteMandataireIndividuel.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/enqueteMandatairePrepose.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/queries.js
packages/app/src/components/Enquete/EnquetePrepose/enquetePreposeMenuBuilder.service.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationAutres.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationAutresForm.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationAutresFormMapper.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationAutresFormSchema.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationMjpm.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationMjpmForm.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationMjpmFormMapper.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/EnquetePreposePersonelFormationMjpmFormSchema.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/mutations.js
packages/app/src/components/Enquete/EnquetePreposePersonelFormation/queries.js
packages/hasura/metadata/tables.yaml
packages/knex/migrations_v2/20200609142319_upd_enquete_reponses_prepose_personel_formation.js

feat(enquete): prepose personel et formation autres

---

packages/api/src/routes/hasura-actions/enquete/common/enquete-status/enqueteSchemaUtil.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/index.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel/enqueteMandataireIndividuelStatus.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/enqueteMandatairePreposeStatus.js

Fix global status calculation.

feat(enquete): fix top level global status

---

packages/api/src/routes/hasura-actions/enquete/common/excel-parser/enqueteExcelParserActivite.js
packages/app/src/components/Enquete/EnqueteIndividuel/EnqueteIndividuelSubmit.js
packages/app/src/components/Enquete/EnqueteIndividuel/enqueteIndividuelMenuBuilder.service.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsAgrement.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsAgrementForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsMandataire.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/index.js
packages/app/src/components/Enquete/EnquetePrepose/EnquetePreposeSubmit.js

fix(enquete): individuel issues

---

packages/app/src/components/Enquete/EnqueteForm/EnqueteFormInputField.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsAgrementForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsFormationForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsMandataireForm.js
packages/app/src/components/Enquete/EnqueteIndividuelPrestationsSociales/EnqueteIndividuelPrestationsSocialesForm.js

feat(enquete): lecture seule - individuels #1911

---

packages/app/pages/mandataires/enquetes/[enquete_id]/index.js
packages/app/src/components/Enquete/EnqueteIndividuel/EnqueteIndividuel.js
packages/app/src/components/Footer/Footer.js
packages/app/src/components/Footer/style.js
packages/app/src/components/Layout/LayoutMandataire.js
packages/app/src/components/MenuStepper/style.js

⚠️ Il faudrait tester sur IE avant de merger

feat(enquete): sticky menu - it fixes #1944

---

packages/api/src/routes/hasura-actions/enquete/common/enquete-status/activite/activiteSchemaUtil.js
packages/app/src/components/Enquete/EnqueteActivite/common/EnqueteActiviteFormGroupMesures.js
packages/app/src/components/Enquete/EnqueteActivite/common/buildMesureGroupsAttributes.js

fix(enquete): activite champs facultatifs

---

packages/api/src/middlewares/hasura-error-handler.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel/requests.js
packages/app/src/components/Enquete/EnqueteCommon/EnqueteWelcome.js

A l'initialisation de la réponse d'un mandataire, l'api crash si pas de département.

fix(enquete): fix bug init mandataire

---

packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsFormationForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsMandataireForm.js
packages/app/src/components/EnqueteImport/EnqueteImportPanel.js
packages/app/src/components/EnqueteImport/useEnqueteImportManager.hook.js
packages/app/src/util/index.js

fix(enquete): fix form bugs & prevent import if not draft #1801

---

packages/api/src/routes/hasura-actions/enquete/common/enquete-status/prepose-personnel-formation/enquetePreposePersonnelFormationStatus.js
packages/api/src/routes/hasura-actions/enquete/hasura-actions.enquetes.checker.js
packages/api/src/routes/hasura-actions/enquete/hasura-actions.enquetes.routes.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel-import/mandataireIndividuelEnqueteRepository.js
packages/api/src/routes/hasura-actions/enquete/mandataire-individuel/enqueteMandataireIndividuel.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose-import/preposeEnqueteRepository.js
packages/api/src/routes/hasura-actions/enquete/mandataire-prepose/enqueteMandatairePrepose.js
packages/api/src/routes/hasura-actions/enquete/service/enqueteService.js
packages/app/src/components/Enquete/EnqueteCommon/EnqueteSubmit.js
packages/app/src/components/Enquete/EnqueteIndividuel/mutations.js
packages/app/src/components/Enquete/EnquetePrepose/mutations.js
packages/app/src/components/Enquete/EnquetePreposePersonnelFormation/EnquetePreposePersonnelFormationAutresFormSchema.js
packages/app/src/components/EnqueteImport/EnqueteImportPanel.js
packages/hasura/metadata/actions.graphql
packages/hasura/metadata/actions.yaml

Toub/feat enquete gérer proprement la soumission du formulaire 1914

---

packages/api/src/routes/hasura-actions/enquete/common/enquete-status/agrements_formations/enqueteAgrementsFormationsStatus.js
packages/api/src/routes/hasura-actions/enquete/common/enquete-status/informations_mandataire/enqueteInformationsMandatairesStatus.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsFormationForm.js

@tglatt  Faire le point en vocal avant de merger

fix(enquete): it fixes #2009

---

packages/app/src/components/EnqueteDirection/DirectionEnqueteDetails.js
packages/app/src/components/EnqueteDirection/DirectionEnqueteDetailsReponsesList.js
packages/app/src/components/EnqueteDirection/DirectionEnqueteReponsesFilter/DirectionEnqueteReponsesCriteria.js
packages/app/src/components/EnqueteDirection/DirectionEnqueteReponsesFilter/enqueteReponseResumesFilter.service.js
packages/app/src/components/EnqueteDirection/DirectionEnqueteReponsesFilter/useDirectionEnqueteReponsesCriteria.hook.js
packages/app/src/components/EnqueteDirection/directionEnqueteReponseResumeBuilder.js
packages/app/src/components/EnqueteDirection/queries.js
packages/hasura/metadata/tables.yaml

Toub/feat enquete dashboard direction affichage des mandataires et services n'ayant pas encore répondu

---

packages/api/__test__/e2e/api/__snapshots__/mesures.test.js.snap
packages/api/__test__/e2e/api/mesures.test.js
packages/api/package.json
packages/api/src/routes/api/editors.js
yarn.lock

feat(api): add checks for mesure creation

---

packages/api/__test__/e2e/api/__snapshots__/mesures.test.js.snap
packages/app/src/components/ListeBlanche/ListeBlanche.js
packages/app/src/components/ListeBlanche/ListeBlanchePrepose/ListeBlanchePreposeItem.js
packages/app/src/components/ListeBlanche/queries.js
packages/app/src/components/ListeBlancheFilter/ListeBlancheFilter.js
packages/app/src/components/ListeBlancheSummary/ListeBlancheSummary.js
packages/app/src/components/ListeBlancheSummary/queries.js

fix(liste-blanche): preposes

---

.gitlab-ci.yml
.gitlab-ci/env.sh
packages/api/.k8s.values.yml
packages/app/.k8s.values.yml
packages/hasura/.k8s.values.yml

Modifs pour atterrir sur le nouveau cluser

fix(ci): use cluster 2

---

.gitlab-ci.yml
.k8s/app-redirect.yml

This adds an ingress for emjpm.num.social.gouv.fr that 301 redirects to emjpm.fabrique.social.gouv.fr

fix(ci): add ingress redirection for emjpm.num.*

---

.k8s/app-redirect.yml

fix(ci): fix redirect ingress namespace

---

packages/app/src/components/MagistratMandataire/MagistratMandataire.js
packages/app/src/components/MagistratMesureMandataire/MagistratMesureMandataire.js
packages/ui/src/components/MandataireListItem/MandataireListItem.js

feat(mandataires): show zipcode - it closes #2201

---

packages/api/src/controllers/user/signup.js
packages/api/src/models/Direction.js
packages/app/src/components/AppForm/FormGroupSelect.js
packages/app/src/components/Signup/SignupDirection.js
packages/app/src/components/Signup/SignupMagistrat.js
packages/app/src/components/Signup/SignupService.js
packages/app/src/components/Signup/SignupServiceInvitation.js
packages/app/src/components/Signup/context/SignupContext.js
packages/app/src/components/Signup/queries.js
packages/app/src/util/option/OptionUtil.js

feat(signup): add department and region in form

---

docker-compose.yaml

fix(docker-compose-machine-reboot): always restart services

---

.gitlab-ci.yml

chore(gitlab-ci): put "Init Managed Database" in deploy stage

---

packages/app/src/components/AdminServices/mutations.js
packages/app/src/components/AdminUserMandataire/mutations.js
packages/app/src/components/MesureDelete/mutations.js
packages/hasura/migrations/1607956544726_mesure_fk_cascade/down.sql
packages/hasura/migrations/1607956544726_mesure_fk_cascade/up.sql

refactor(mesure): delete cascade

---

packages/app/pages/admin/liste-blanche/[id]/delete.js
packages/app/src/components/AdminLbUserDelete/AdminLbUserDelete.js
packages/app/src/components/AdminLbUserDelete/AdminLbUserDeleteForm.js
packages/app/src/components/AdminLbUserDelete/index.js
packages/app/src/components/AdminLbUserDelete/mutations.js
packages/app/src/components/AdminLbUserDelete/style.js
packages/app/src/components/ListeBlanche/ListeBlancheIndividuel/ListeBlancheIndividuelForm.js
packages/app/src/components/ListeBlanche/ListeBlancheMandataires.js
packages/app/src/components/ListeBlanche/ListeBlanchePrepose/ListeBlanchePreposeForm.js
packages/hasura/migrations/1607967494636_lb_user_fk_cascade/down.sql
packages/hasura/migrations/1607967494636_lb_user_fk_cascade/up.sql

feat(admin-lb-delete): admin list-blanche delete mandataire

---

packages/app/src/components/ListeBlanche/ListeBlancheIndividuel/ListeBlancheIndividuelForm.js
packages/app/src/components/ListeBlanche/ListeBlanchePrepose/ListeBlanchePreposeForm.js

https://github.com/SocialGouv/emjpm/pull/2363/files#r543134556

fix(liste-blanche): delete mandataire seulement visible par admin

---

packages/app/src/components/AuthorizationLogin/AuthorizationLogin.js
packages/app/src/components/EditPassword/EditPassword.js
packages/app/src/components/ForgotPassword/ForgotPassword.js
packages/app/src/components/Login/Login.js
packages/app/src/components/ResetPassword/ResetPassword.js
packages/app/src/components/Signup/signup.js
packages/app/src/util/geocode/geocode.js

thanks @revolunet for this patch hoping this will resolve the firefox 52 bug we have

fix(login-on-ff52): fetch credentials include

---

packages/app/src/components/AuthorizationLogin/AuthorizationLogin.js
packages/app/src/components/Login/Login.js
packages/app/src/lib/apollo/init-apollo.js
packages/app/src/matomo.js
packages/app/src/util/auth.js

fix #2406
implementing https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/ in progress

refactor(auth): in memory token + enable matomo userid

---

docker-compose.prod.local.yaml
docker-compose.yaml
docs/ERM.graphml
docs/workflows/liste-blanche-utilisateur.md
docs/workflows/mesures.md
docs/workflows/users-workflow.md

fix #2411
and resolve some points of #2401

docs(emjpm): erm+biz

---

.gitlab-ci.yml

ci(trivy-scan): add to gitlab-ci

---

packages/app/src/components/AppForm/FormGroupInput.js
packages/app/src/components/Signup/SignupServiceInvitation.js
packages/app/src/components/Signup/SignupServiceInvitationForm.js
packages/app/src/hooks/useSearchParams.js
packages/app/src/pages/admin/etablissements/[id].js
packages/app/src/pages/admin/etablissements/add.js
packages/app/src/pages/signup/invitation.js
packages/app/src/routes/Routes.js
packages/app/src/util/useQuery.js
packages/hasura/metadata/tables.yaml

fix https://github.com/SocialGouv/emjpm/security/advisories/GHSA-xh5v-f2xq-9w4x
and many little things

fix(things): security + bugs + routes

---

packages/app/src/containers/IndicatorList/IndicatorList.js
packages/app/src/containers/IndicatorList/IndicatorListTotal.js
packages/app/src/containers/IndicatorList/queries.js
packages/hasura/metadata/tables.yaml

fix(stats): public same as direction

---

.github/workflows/ci.yml

ci(github): update to actions/setup-node@v2.2.0

---

.k8sci/scripts/deploy

use new certmanager annotations

fix(ci): use kube 1.2 ingress annotations
