.gitignore

ignore default override for production

chore: add docker-compose.override.yaml to gitignore

---

packages/app/src/piwik.js

Il semblerait que parfois ceci plante, malgré que le JWT soit valide...
https://sentry.num.social.gouv.fr/incubateur/emjpm/issues/350/

fix: prevent some exceptions witj JWT decoding

---

docker-compose.yaml

can be useful when we need to run commands on specific containers (ex: backups)

fix(docker): use a static container_name

---

packages/api/__test__/e2e/mandataires/GET_postcode.test.js
packages/api/__test__/e2e/mandataires/__snapshots__/GET_postcode.test.js.snap
packages/api/db/queries/geolocalisation_code_postal.js
packages/api/db/queries/mandataires.js
packages/api/routes/mandataires.js
packages/app/src/components/tiComponents/MapTi.js
packages/app/src/components/tiComponents/actions/map.js

---
**BREAKING CHANGE**: remove POST /mandataires/PosteCode route
It feel more natural to get the postcodes from a `GET` method.

feat(api): add GET /mandataires/postcode/:postcode route

---

.gitlab-ci.yml
optional/e2e/Dockerfile
packages/app/nginx.conf

- use a variable in proxy_pass destination so nginx container can startup even when target is down
- use a k8s friendly service name

ci(gitlab): make the e2e tests run - not work

---

package.json

--- 
As `@optional/e2e` is an optional package. 
`yarn` doesn't install cypress by default

build(monorepo): ignore @optional/e2e package

---

.gitlab-ci.yml
Dockerfile
README.md
docker-compose.override.yaml.sample
packages/app/Dockerfile
packages/app/next.config.js
packages/app/nginx.conf

Plusieurs fixes pour pouvoir faire tourner un environnement docker-compose from scratch :
- passage des `ARG` de build docker pour l'app statique
- possibilité de build les images docker localement et de passer le `BASE_IMAGE` à docker-compose
- gitlab-ci : rename du service `emjpm__api` en `api`
- ajout d'un service docker-compose `knex` basé sur l'image docker principale qui permet de run des commandes knex sur un env existant (ex: migrate, seeds...)

fix(docker): make BASE_IMAGE configurable

---

packages/app/nginx.conf

Ensure that nginx starts even if the api is not up
Partial revert https://github.com/SocialGouv/emjpm/commit/274aae79ce28ca3bdc16a657bd7efd2317fb27bd 
\following https://github.com/SocialGouv/emjpm/pull/247

build(app): re-use a $upstream variable in nginx config

---

.dockerignore

---
BEFORE
```
$ docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT
Sending build context to Docker daemon  24.57MB
```
AFTER
```
$ docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT
Sending build context to Docker daemon  3.332MB
```

build(docker): ignore more stuff

---

packages/app/src/components/inscription/Form.js

Prevent `Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

fix(app): add missing returns

---

packages/knex/knexfile.js

The uesr `emjpm` can't change triggers
```
$ yarn workspace @emjpm/knex run migrate --env test      
yarn workspace v1.17.3
yarn run v1.17.3
$ knex migrate:latest --env test
Using environment: test
migration file "20190923112826_update_trigger_mesures_counter.js" failed
migration failed with error: 
DROP TRIGGER on_update_mesures ON mesures;
DROP FUNCTION update_gestionnaire_counters;
CREATE OR REPLACE FUNCTION update_gestionnaire_counters() RETURNS trigger AS $$
BEGIN
IF (TG_OP = 'UPDATE' and new.antenne_id is not null) THEN
perform update_antenne_counters(new.antenne_id);
IF (old.antenne_id  <> new.antenne_id) THEN
perform update_antenne_counters(old.antenne_id);
END IF;
return new;
elseif (TG_OP = 'UPDATE' and new.mandataire_id is not null) then perform …
```

fix(knex): use postgres user locally

---

packages/app/package.json

Required by "@emjpm/app > next > native-url@0.2.3" has unmet peer dependency "@types/node@>=8.0.0".

chore(app): add @types/node peer dependency

---

packages/app/package.json
yarn.lock

Required by :
- @emjpm/app > react-apollo@3.1.3" has unmet peer dependency "@types/react@^16.8.0".
- @emjpm/app > react-apollo@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
- @emjpm/app > react-apollo > @apollo/react-common@3.1.3" has unmet peer dependency "@types/react@^16.8.0"

chore(app): add @types/react peer dependency

---

packages/api/package.json
yarn.lock

Required by:
- @emjpm/api > objection-db-errors@1.1.2" has unmet peer dependency "objection@>= 0.9.1".

chore(api): add objection peer dependency

---

.k8s/postgres/dataset/job-inject-dataset.yml

build(k8s): allow data injection job to go up to 0.5 CPU

---

packages/app/src/components/AdminServices/AdminServiceMesures.js
packages/app/src/components/AdminServices/queries.js
packages/app/src/components/AdminUsers/AdminUsersMesures.js
packages/app/src/components/AdminUsers/queries.js
packages/app/src/constants/mesures.js

Fix https://github.com/SocialGouv/emjpm/issues/1714
Sur la page d'un utilisateurs dans l'espace administrateur, je souhaite:
Sur la page d'un service de l'espace administrateur, je souhaite:

feat(admin): affichage des mesures

---

package.json
yarn.lock

Le seul breaking change, c'est node>=10
https://github.com/typicode/husky/releases/tag/v4.0.0

chore(deps): update husky

---

packages/app/src/components/EnqueteImport/EnqueteImportPanel.js

Au final, le plus simple et le plus `safe` c'est de vider complètement le cache, car il y a trop de requêtes concernées par cet import.

feat(enquetes): clear apollo store after import

---

packages/api/src/routes/hasura-actions/enquete/common/enquete-status/informations_mandataire/enqueteInformationsMandatairesStatus.js
packages/app/src/components/Enquete/EnqueteIndividuel/enqueteIndividuelMenuBuilder.service.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsFormationForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsMandataire.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsMandataireForm.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/EnqueteIndividuelInformationsMandataireForm.test.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/index.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/mutations.js
packages/app/src/components/Enquete/EnqueteIndividuelInformations/queries.js
packages/app/src/components/EnqueteImport/EnqueteImportPanel.js

Correction enquêtes mandataire #1889 #1801
__Onglet informations générales__
__Onglet formation__

feat(enquete): fix mandataire infos generales + formation

---

packages/app/src/components/Enquete/EnqueteActivite/common/EnqueteActiviteFormGroupMesures.js
packages/app/src/components/Enquete/EnqueteForm/EnqueteFormInputField.js
packages/app/src/components/Enquete/EnqueteForm/EnqueteFormSelectField.js
packages/app/src/components/Enquete/EnqueteForm/EnqueteFormYesNoField.js
packages/app/src/components/Enquete/EnqueteForm/EnqueteInlineError.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationTrancheAgeField.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationsForm.js
packages/app/src/components/Enquete/EnquetePreposeFinancement/EnquetePreposeFinancementForm.js
packages/app/src/components/Enquete/EnquetePreposePrestationsSociales/EnquetePreposePrestationsSocialesAutresMesures.js
packages/app/src/components/Enquete/EnquetePreposePrestationsSociales/EnquetePreposePrestationsSocialesCuratelleRenforcee.js
packages/app/src/components/Enquete/EnquetePreposePrestationsSociales/EnquetePreposePrestationsSocialesCuratelleSimple.js
packages/app/src/components/Enquete/EnquetePreposePrestationsSociales/EnquetePreposePrestationsSocialesMAJ.js
packages/app/src/components/Enquete/EnquetePreposePrestationsSociales/EnquetePreposePrestationsSocialesTutelle.js

feat(enquete): fix inline error alignment #1956

---

packages/app/src/components/EnqueteDirection/DirectionEnqueteReponseResumeCard.js

Pour rappel le problème vient qu'un des mandataire n'a pas l'agrément sur le département du compte direction connecté (donc impossible de récupérer son nom à cause des permissions hasura).

fix(enquetes): critical issue with direction account

---

.env.sample
docker-compose.yaml
packages/api/knexfile.js
packages/app/next.config.js
packages/app/src/lib/apollo/init-apollo.js

cette PR termine de résoudre la PR #2323 et l'issue #2322
ça y est cette fois ci on peut se connecter et utiliser l'app normalement
@tglatt dans le .env
```
HASURA_GRAPHQL_URI=http://graphql-engine:8080/v1/graphql
GRAPHQL_SERVER_URI=http://localhost:5000/v1/graphql
GRAPHQL_SERVER_URI_DOCKER=http://graphql-engine:8080/v1/graphql
```
voir:
https://github.com/apollographql/apollo-link/issues/375#issuecomment-514840117
https://medium.com/@semur.nabiev/get-graphql-apollo-to-work-with-nextjs-ssr-within-docker-aa179ff0c2bc
PS:
`packages/api/knexfile.js` ne semble pas consommer le .env à la racine du projet, c'est ce que revèle un console.log sur `process.env.DATABASE_URL` donc, étant donné qu'il utilise les réglages par défaut (hardcodés), j'ai du changer le port de 5434 en 5432 pour l'env …

fix(app-in-docker-compose): can now connect and use app as before

---

packages/app/pages/admin/users/[user_id].js
packages/app/pages/admin/users/[user_id]/delete.js
packages/app/src/components/AdminServices/AdminServiceMesures.js
packages/app/src/components/AdminUser/AdminUser.js
packages/app/src/components/AdminUser/queries.js
packages/app/src/components/AdminUserActivation/AdminUserActivation.js
packages/app/src/components/AdminUserDelete/AdminUserDelete.js
packages/app/src/components/AdminUserDelete/AdminUserDeleteForm.js
packages/app/src/components/AdminUserDelete/index.js
packages/app/src/components/AdminUserDelete/mutations.js
packages/app/src/components/AdminUserDelete/style.js
packages/app/src/components/AdminUserMandataire/AdminMandataireMesures.js
packages/app/src/components/AdminUsers/AdminUsers.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationsAutreMesures.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationsCuratelle.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationsMAJ.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationsSauvegardeJustice.js
packages/app/src/components/Enquete/EnquetePopulations/EnquetePopulationsTutelle.js
packages/app/src/lib/validationSchemas/adminUserDeleteSchema.js
packages/app/src/lib/validationSchemas/index.js
packages/hasura/migrations/1607615995461_user_fk_cascade/down.sql
packages/hasura/migrations/1607615995461_user_fk_cascade/up.sql

UI: OK (enfin il me semble, à moins qu'il faille rajouter un champs texte pour enregistrer la raison de la supression)
Migration: j'ai opté pour un delete en cascade, selon la team hasura c'est la bonne option (see https://github.com/hasura/graphql-engine/issues/1736#issuecomment-471937346), j'ai trouvé la commande squash dont tu m'as parlé sur la migration hasura ;)
J'ai aussi nettoyé l'URI sur admin/users/[user_id], plutôt que d'accorder une confiance aux paramètres `type` et `active` dans l'url je me suis basé sur l'user_id pour les charger (ce qui a simplifié la navigation, sinon on aurais continué à s'embourber là dedans en relayant sans cesse ces paramètres).
Au moment de commiter le linter m'a forcé de manière intransigeante à mettre des useMemo un peu partout dans des fichiers sur …

feat(admin-user): delete inactive user
